Add imports to terraform plan result
pipe-cd/pipecd pull request #4412
Opened 2023-06-21 03:49 UTC by khanhtc1202

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4401

**Does this PR introduce a user-facing change?**:

```release-note
Support Terraform v1.5.0 and later which introduces import feature
```

2023-06-21 06:32 UTC, khanhtc1202 commented on pkg/app/piped/platformprovider/terraform/terraform.go
> +		var impt, add, change, destroy string
Take a close look, you can see these variables are not returned one, but they are used to store vals[i] data 😄

2023-06-21 06:58 UTC, sivchari commented on pkg/app/piped/platformprovider/terraform/terraform.go
> +		var impt, add, change, destroy string
Oops, I overlooked 🐱

2023-06-21 12:36 UTC, kentakozuka requested changes
Nice :)
Left some comments. PTAL

2023-06-21 12:36 UTC, kentakozuka commented on pkg/app/piped/platformprovider/terraform/terraform_test.go
> +			}
This test passes even if the `expected` is unexpected.
How about simply writing this?

```suggestion
			assert.Equal(t, tc.expected, result)
```

2023-06-21 14:26 UTC, khanhtc1202 commented on pkg/app/piped/platformprovider/terraform/terraform.go
> +	if s := planHasChangeRegex.FindStringSubmatch(out); len(s) > 0 {
Oops, you're right. Have to fix the regex to extract both import available and not available case 👍

2023-06-22 04:06 UTC, khanhtc1202 commented on pkg/app/piped/platformprovider/terraform/terraform.go
> +	if s := planHasChangeRegex.FindStringSubmatch(out); len(s) > 0 {
Updated, thank you 👍

2023-06-22 10:55 UTC, khanhtc1202 commented
@kentakozuka PTAL when you have time 🙏

2023-06-22 11:02 UTC, kentakozuka approved these changes
Superb 😄

2023-06-22 11:02 UTC, merged